### PR TITLE
Remove 'fs' dependency

### LINKED ISSUE #20: No need to use fs as npm dependency
Hi!
`fs` is a node core module, there is no need to include it as npm dependency
See https://github.com/npm/npm/issues/13743

### PR DESCRIPTION
**Pull request by pdehaan**
Ref: https://www.npmjs.com/package/fs

Fixes #20

### CODE REVIEW

**Comment by stockulus** [comment]
Hi,

see the Problem with the fs Package, but it is still needed.

screen shot 2016-08-25 at 07 36 10

There has to be changed parts of the levelDB adapter too. So I had to undo the change.

**Comment by YurySolovyov** [comment]
@stockulus where this error is coming from?

**Comment by stockulus** [comment]
this came pouchdb-adapter-leveldb-core-rn/migrate.
(this is a copy of pouchDB level adapter with some tweets for react native)
I fixed this, but it did not really help, there are other leveldb dependencies using fs
(e. g. binding)

**Comment by stockulus** [comment]
Properly the best solution is moving forward, and get rid of the leveldown dependencies

**Comment by YurySolovyov** [comment]
This is really weird because there is literally nothing in this module
```
$ npm i fs
/home/y.solovyov/t
└── fs@0.0.1-security

$ ls node_modules/fs/
package.json  README.md
```
same for `0.0.2`
> there are other leveldb dependencies using fs

Can you point me to these?

**Comment by stockulus** [comment]
grep -r "'fs'" packages/pouchdb-adapter-asyncstorage/node_modules/*

**Pull request merged**
